"""Memory consolidation: deterministic dedupe + optional LLM dream (flagged)."""

from __future__ import annotations

import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from kageha.config import kageha_home
from kageha.memory.models import MemoryKind, MemoryState
from kageha.memory.store import MemoryStore


@dataclass
class ConsolidateReport:
    superseded_duplicates: int = 0
    expired_quarantine: int = 0
    dream_superseded: int = 0
    digest_path: str = ""
    skipped_cooldown: bool = False
    dream: dict[str, Any] = field(default_factory=dict)
    details: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "superseded_duplicates": self.superseded_duplicates,
            "expired_quarantine": self.expired_quarantine,
            "dream_superseded": self.dream_superseded,
            "digest_path": self.digest_path,
            "skipped_cooldown": self.skipped_cooldown,
            "dream": self.dream,
            "details": self.details[:40],
        }


def consolidate_cooldown_hours() -> float:
    raw = (os.environ.get("KAGEHA_MEMORY_CONSOLIDATE_HOURS") or "6").strip()
    try:
        return max(0.0, float(raw))
    except ValueError:
        return 6.0


def _token_set(text: str) -> set[str]:
    return {t for t in "".join(ch.lower() if ch.isalnum() else " " for ch in text).split() if len(t) > 2}


def _near_duplicate(a: str, b: str) -> bool:
    ta, tb = _token_set(a), _token_set(b)
    if not ta or not tb:
        return False
    overlap = len(ta & tb) / max(1, min(len(ta), len(tb)))
    return overlap >= 0.85


def should_skip_consolidate(store: MemoryStore) -> bool:
    hours = consolidate_cooldown_hours()
    if hours <= 0:
        return False
    event = store.latest_event("consolidate")
    if not event:
        return False
    age_h = (time.time() - float(event.get("created_at") or 0.0)) / 3600.0
    return age_h < hours


def write_memory_digest(store: MemoryStore) -> Path:
    """Claude-style compact MEMORY.md index (pointers, not authority)."""
    path = kageha_home() / "memory" / "MEMORY.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = store.list_memories(state=MemoryState.CONFIRMED.value, limit=200)
    prefs = [
        r
        for r in rows
        if r.kind
        in {
            MemoryKind.INSTRUCTION.value,
            MemoryKind.PREFERENCE.value,
            MemoryKind.USER_FACT.value,
        }
        and r.source_role == "user"
    ]
    prefs.sort(key=lambda r: r.updated_at, reverse=True)
    others = [r for r in rows if r not in prefs]
    others.sort(key=lambda r: r.updated_at, reverse=True)

    lines = [
        "# MEMORY.md",
        "",
        "Compact index generated by Kageha consolidate. SQLite remains authority.",
        "Use memory_fetch / memory_recall for full claims.",
        "",
        "## Standing instructions & preferences",
        "",
    ]
    if not prefs:
        lines.append("(none)")
    for rec in prefs[:40]:
        one = " ".join(rec.content.split())
        if len(one) > 140:
            one = one[:139] + "…"
        lines.append(f"- [{rec.kind}] {one} `[{rec.id}]`")
    lines.extend(["", "## Recent project facts & decisions", ""])
    if not others:
        lines.append("(none)")
    for rec in others[:40]:
        one = " ".join(rec.content.split())
        if len(one) > 120:
            one = one[:119] + "…"
        lines.append(
            f"- [{rec.kind}/{rec.scope_type}] {one} `[{rec.id}]`"
        )
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path


def consolidate_store(store: MemoryStore, *, force: bool = False) -> ConsolidateReport:
    report = ConsolidateReport()
    if not force and should_skip_consolidate(store):
        report.skipped_cooldown = True
        report.dream = {"enabled": False, "applied": 0, "reason": "cooldown"}
        return report

    confirmed = store.list_memories(state=MemoryState.CONFIRMED.value, limit=1000)
    # 1) Same claim_key + scope → keep newest
    by_claim: dict[tuple[str, str, str], list] = {}
    for rec in confirmed:
        key = (rec.claim_key, rec.scope_type, rec.scope_key)
        by_claim.setdefault(key, []).append(rec)
    for group in by_claim.values():
        if len(group) < 2:
            continue
        group.sort(key=lambda r: r.updated_at, reverse=True)
        keep = group[0]
        for old in group[1:]:
            store.update_state(
                old.id,
                MemoryState.SUPERSEDED.value,
                supersedes_id=keep.id,
            )
            report.superseded_duplicates += 1
            report.details.append(
                {
                    "action": "supersede_claim_duplicate",
                    "kept": keep.id,
                    "dropped": old.id,
                }
            )

    # Refresh after claim collapse
    confirmed = store.list_memories(state=MemoryState.CONFIRMED.value, limit=1000)
    # 2) Near-duplicate content within the same scope bucket (keep newest).
    buckets: dict[tuple[str, str], list] = {}
    for rec in confirmed:
        buckets.setdefault((rec.scope_type, rec.scope_key), []).append(rec)
    for group in buckets.values():
        group.sort(key=lambda r: r.updated_at, reverse=True)
        kept: list = []
        for rec in group:
            dup_of = next(
                (other for other in kept if _near_duplicate(rec.content, other.content)),
                None,
            )
            if dup_of is None:
                kept.append(rec)
                continue
            store.update_state(
                rec.id,
                MemoryState.SUPERSEDED.value,
                supersedes_id=dup_of.id,
            )
            report.superseded_duplicates += 1
            report.details.append(
                {
                    "action": "supersede_near_duplicate",
                    "kept": dup_of.id,
                    "dropped": rec.id,
                }
            )

    # 3) Age out old quarantined noise
    quarantine_ttl = float(os.environ.get("KAGEHA_MEMORY_QUARANTINE_TTL_DAYS", "30"))
    now = time.time()
    for rec in store.list_memories(state=MemoryState.QUARANTINED.value, limit=1000):
        age_days = (now - (rec.updated_at or rec.created_at)) / 86400.0
        if age_days < max(1.0, quarantine_ttl):
            continue
        store.update_state(rec.id, MemoryState.EXPIRED.value)
        report.expired_quarantine += 1
        report.details.append(
            {"action": "expire_quarantine", "id": rec.id, "age_days": round(age_days, 1)}
        )

    # 4) Optional LLM dream (default off). Never required for correctness.
    from kageha.memory.dream import dream_consolidate, llm_dream_enabled

    if llm_dream_enabled():
        dream = dream_consolidate(store)
        report.dream = dream
        report.dream_superseded = int(dream.get("applied") or 0)
        report.superseded_duplicates += report.dream_superseded
        report.details.extend(list(dream.get("details") or [])[:20])
    else:
        report.dream = {"enabled": False, "applied": 0}

    digest = write_memory_digest(store)
    report.digest_path = str(digest)
    store.add_event("consolidate", report.to_dict())
    return report
